apiVersion: v1
kind: Service
metadata: 
  name: web
  namespace: roboshop
spec: 
  selector: 
    app: web
    tier: web
    project: roboshop
  ports:
  - name: web-port
    protocol: TCP
    port: 80  #this is service port 
    targetPort: 80 #this port belongs to container

